### PR TITLE
added ajax call for youtube search API

### PR DESCRIPTION
**Pull request by code-guy21**

### CODE REVIEW

**Comment by JoshBal117** [comment]
This an amazing piece of code, nothing else to see here

**Review by kyled871 — COMMENTED** [review]
nice!

**Review by JoshBal117 — COMMENTED** [review]
Greatest Code here so far

**Comment by JoshBal117** [comment]
This needs to be added, Alexis did an amazing job:

**Review by kyled871 — APPROVED** [review]
looks good!

**Pull request merged**
